### ISSUE TITLE
The New Event-Based User Input System - TODO and bug-fixes

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#700]
This is a follow up of changes that are yet to be made following the implementation of conrod's new event-based user input system in #684 as discussed in #670.

#### Widgets that still need to be changed over to the new system:

- [x] Button
- [x] DropDownList
- [ ] EnvelopeEditor
- [ ] NumberDialer
- [ ] Slider
- [ ] Tabs (maybe?)
- [ ] TextBox
- [ ] TitleBar
- [ ] Toggle
- [ ] XYPad
- [ ] CircularButton (from custom_widget.rs example)

#### Other related todo:

- [ ] Review the `Widget::drag_area` method and related types and see if these can be removed in favour of using the new `Drag` events.
- [ ] Fix bug where widgets still receive `Clicked` events when covered by another widget (should be using `Graph::pick_widget` method).

**Comment by mitchmindtree** [comment]
@psFried I'm currently working away on the above and I noticed that we're creating drag events upon raw release events - I'm thinking of refactoring this to only generate drag events on raw move events as this feels a little more intuitive to me, but I'm curious to hear what your thoughts are on this first?

**Comment by mitchmindtree** [comment]
Ahh, I just noticed the `in_progress` field in the `MouseDrag` struct.

How about rather than combining state into the one `MouseDrag` event, we add `DragStart` and `DragEnd` events?

Also, I'm thinking of changing `MouseDrag` -> `Drag` and `MouseClick` -> `Click`, thoughts?

**Comment by mitchmindtree** [comment]
Going to close this issue in favour of tracking progress at #703
