### ISSUE TITLE
`TextEdit` todo list

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#729]
#703 adds a multi-line `TextEdit` widget, but it still requires a lot of work:

- [ ] Insert a newline on `Return`/`Enter`.
- [ ] Add functionality for `Up` and `Down` arrow keys.
- [ ] Add clipboard functionality.
- [ ] Fix bug where cursor sometimes jumps to the start of the line when entering text at the end of a line.
- [ ] Fix issue where `Text` widget is slightly offset from drawn selection rectangles when `TextEdit` is aligned to the middle of bottom of the *y* axis. Doesn't seem to be a problem when aligned to the top.

**Comment by christolliday** [comment]
So with https://github.com/PistonDevelopers/conrod/issues/796 I think the only issue left is the clilpboard.

I think the best option for cross-platform clipboard support is to depend on https://github.com/aweinstock314/rust-clipboard. The only problem is parts of it are GPLv2, but apparently there are some plans to rewrite those parts, so maybe the easiest thing to do is to wait for that. I think otherwise we would have to relicense as GPL?

**Comment by akhilman** [comment]
https://github.com/chrisduerr/rust-clipboard have Apache and MIT license.
