### ISSUE TITLE
Small EnvelopeEditor Fixes

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/conrod#99]
EnvelopeEditors are currently usable though still require a few fixes.
- [x] The auto-determined precision for the value labels needs to be tweaked.
- [ ] Add an option for curve-able envelopes (using bezier curves).
- [ ] When hovering above pad, show semi-transparent insertion lines from nearest points. #100
- [ ] Implement crosshair from xy_pad.
- [ ] Implement `Gridding` enum when it lands. #85
- [x] Fix issue where an EnvelopePoint's label and circle moves if it is right clicked and dragged. #101

Feel free to add any other tweaks - it's one of the more complex widgets so I imagine different people will have different expectations of its behaviour.
